"use strict";
exports.__esModule = true;
var mobile_1 = require("./mobile");
var mobileLibrary_1 = require("./mobileLibrary");
var mobile1 = new mobile_1.Mobile("Nokia3210", "3210", "Nokia", "big", "gray", true, 2, 500);
var mobile2 = new mobile_1.Mobile("iPhone3G", "3G", "Apple", "small", "black", false, 3, 1000);
var mobile3 = new mobile_1.Mobile("Samsung Galaxy 10", "Galaxy 10", "Samsung", "medium", "white", false, 1, 899);
var mobile4 = new mobile_1.Mobile("Pocophone", "Pocophone", "Xiaomi", "medium", "red", true, 3, 400);
var mobiles = [mobile1, mobile2, mobile3, mobile4];
var mobiles2 = [mobile1, mobile4];
var libreria1 = new mobileLibrary_1.MobileLibrary("Espada", "Al lado de casa", mobiles);
// libreria1.setLocation("Ahí");
// libreria1.setMobile(mobiles2);
// libreria1.setName("Cayo Máximo");
// libreria1.setTotalPrice(5000);
// console.log(libreria1.getLocation());
// console.log(libreria1.getMobiles());
// console.log(libreria1.getName());
// console.log(libreria1.getTotalPrice());
libreria1.printLibrary();
